# === Composants par défaut essentiels ===
default_config:

# === Inclusion des notification mobiles ===
mobile_app:

# === Personnalisation de Home Assistant ===
homeassistant:
  packages:
    cumulus_input_select_test: !include packages/cumulus_input_select_test.yaml
    cumulus_core: !include packages/cumulus/core.yaml
    cumulus_sensors_base: !include packages/cumulus/sensors_base.yaml
    cumulus_sensors_calcul: !include packages/cumulus/sensors_calcul.yaml
    cumulus_sensors_monitoring: !include packages/cumulus/sensors_monitoring.yaml
    cumulus_automations_pv: !include packages/cumulus/automations_pv.yaml
    cumulus_automations_hc_safety: !include packages/cumulus/automations_hc_safety.yaml
    carte_batterie: !include packages/carte_batterie.yaml
    git_sync: !include packages/git_sync.yaml
    solaire_economies: !include packages/solaire_economies.yaml
    salle_de_bain: !include packages/salle_de_bain_douche_isa_college.yaml
  customize:
    climate.thermostat_sdb:
      friendly_name: ""
    sensor.energie_entrant_dans_la_solarbank:
      device_class: energy
      state_class: total_increasing
      unit_of_measurement: kWh
    sensor.energie_sortant_de_la_solarbank:
      device_class: energy
      state_class: total_increasing
      unit_of_measurement: kWh

# === Thèmes personnalisés ===
frontend:
  themes: !include_dir_merge_named themes

# === Scripts, automatisations et templates ===
script: !include_dir_merge_named scripts
automation: !include_dir_merge_list automations
template: !include_dir_merge_list templates

# === Dashboards Lovelace ===
lovelace:
  dashboards: !include lovelace/dashboards.yaml

# === Journalisation ===
logger:
  default: warning
