# === Composants par défaut essentiels ===
default_config:

# === Inclusion des notification mobiles ===
mobile_app:

# === Personnalisation de Home Assistant ===
homeassistant:
  packages: !include_dir_named packages    
  customize:
    climate.thermostat_sdb:
      friendly_name: ""
    sensor.energie_entrant_dans_la_solarbank:
      device_class: energy
      state_class: total_increasing
      unit_of_measurement: kWh
    sensor.energie_sortant_de_la_solarbank:
      device_class: energy
      state_class: total_increasing
      unit_of_measurement: kWh

# === Thèmes personnalisés ===
frontend:
  themes: !include_dir_merge_named themes

# === Scripts, automatisations et templates ===
script: !include_dir_merge_named scripts
automation: !include_dir_merge_list automations
template: !include_dir_merge_list templates

# === Dashboards Lovelace ===
lovelace:
  dashboards:
    lovelace-work:
      mode: yaml
      title: Workspace Claude
      icon: mdi:robot
      show_in_sidebar: true
      filename: lovelace/work.yaml
    lovelace-cumulus-corrige:
      mode: yaml
      title: Cumulus Corrigé
      icon: mdi:water-boiler
      show_in_sidebar: true
      filename: lovelace/cards/dashboard_cumulus_corrige.yaml
    lovelace-cumulus-parfaite:
      mode: yaml
      title: Cumulus Parfait
      icon: mdi:water-boiler-alert
      show_in_sidebar: true
      filename: lovelace/cards/lovelace_carte_cumulus_parfaite.yaml
    lovelace-cumulus-styled:
      mode: yaml
      title: Cumulus Styled
      icon: mdi:water-boiler-auto
      show_in_sidebar: true
      filename: lovelace/cards/lovelace_carte_cumulus_styled.yaml

# === Journalisation ===
logger:
  default: warning
